=== MarkZoka/DAW-LMISGI-MarkPires/cataleg.dtd
<!ELEMENT root (element+)>
<!ELEMENT element (#PCDATA)>

<!ELEMENT cataleg (single | album)*>

<!ELEMENT single (titol, descripcio?, pais, idioma, genere*, grup, membres, durada)>
<!ATTLIST single codi CDATA #REQUIRED>

<!ELEMENT album (titol, descripcio?, pais, idioma, genere*, grup, membres, numero_cancons, titols_cancons)>
<!ATTLIST album codi CDATA #REQUIRED>

<!ELEMENT membres (membre+)>

<!ELEMENT membre (nom)>
<!ATTLIST membre sexe (home | dona) #REQUIRED>

<!ELEMENT titols_cancons (canco+)>

<!ELEMENT canco (titol_canco, durada_canco)>
<!ATTLIST canco numero CDATA #REQUIRED>

<!ELEMENT titol (#PCDATA)>
<!ELEMENT descripcio (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT idioma (#PCDATA)>
<!ELEMENT genere (#PCDATA)>
<!ELEMENT grup (#PCDATA)>
<!ELEMENT durada (#PCDATA)>
<!ELEMENT numero_cancons (#PCDATA)>
<!ELEMENT titol_canco (#PCDATA)>
<!ELEMENT durada_canco (#PCDATA)>
<!ELEMENT nom (#PCDATA)>

=== MarkZoka/DAW-LMISGI-MarkPires/cataleg.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cataleg SYSTEM "cataleg.dtd">

<cataleg>

  <single codi="S001">
    <titol>Imagine</titol>
    <pais>UK</pais>
    <idioma>Anglès</idioma>
    <genere>Pop</genere>
    <grup>John Lennon</grup>
    <membres>
      <membre sexe="home">
        <nom>John Lennon</nom>
      </membre>
    </membres>
    <durada>3.1</durada>
  </single>

  <album codi="A001">
    <titol>Thriller</titol>
    <pais>USA</pais>
    <idioma>Anglès</idioma>
    <genere>Pop</genere>
    <genere>Soul</genere>
    <grup>Michael Jackson</grup>
    <membres>
      <membre sexe="home">
        <nom>Michael Jackson</nom>
      </membre>
    </membres>
    <numero_cancons>2</numero_cancons>
    <titols_cancons>
      <canco numero="1">
        <titol_canco>Thriller</titol_canco>
        <durada_canco>5.57</durada_canco>
      </canco>
      <canco numero="2">
        <titol_canco>Beat It</titol_canco>
        <durada_canco>4.18</durada_canco>
      </canco>
    </titols_cancons>
  </album>

</cataleg>
